config/routes.rb
Rails.application.routes.draw do
  get 'logs/index'

  get 'logs/show'

  root 'logs#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  def index
  	@response = Dir["/Users/mybataz/Downloads/*"]
  end

  def show
  	hits = Hash.new(0)
		lar_req = {}
		suc_req = 0
		tota_req = 0
		hour_req = {}
		File.open("#{params['file']}", "r") do |infile|
		  while (line = infile.gets)
		    match = /(GET|POST) (\S+)/.match(line)
		    if match
			    suc_req += 1 if (line.split[line.split.length - 2] == "200")

			    size = line.split[line.split.length - 1]
			    if lar_req.empty?
			    	lar_req[size.to_i] = match[2]
			    elsif (size.to_i > lar_req.keys[0])
			    	lar_req.delete(lar_req.keys[0])
			    	lar_req[size.to_i] = match[2] 
			    end
			end
			tota_req += 1 
			d = line.split[3]
			key = DateTime.strptime(d, "[%d/%b/%Y:%H:%M:%S").strftime("%m/%d/%Y %H")
			hour_req[key].nil? ? (hour_req[key] = 1) : (hour_req[key] += 1)
		    #hits[match[2]] += 1 if match
		  end
		end
		@suc_req = suc_req
		@lar_req = lar_req
		@tota_req = tota_req
		@max_hour_req = (hour_req.max_by{|k,v| v})
		
		# print "Successful requests = #{suc_req}\n"
		# print "Largest request = #{lar_req}\n"
		# print "Total requests = #{tota_req}"
		# print (hour_req.max_by{|k,v| v})
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LogAnalytics</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  	<%= link_to '<button type="button">Log Files</button>'.html_safe, root_path %>
  <body>
    <%= yield %>
  </body>
</html>

app/views/logs/index.html.erb
<h1>Log Files</h1>

<table>
  <tr>
    <th>S.No</th>
    <th>File Name</th>
  </tr>
 
<% @response.each_with_index do |i,v| %>
  <tr>
    <td><%= v+1 %></td>
    <td><%= link_to i, logs_show_path(file: i)%></td>
  </tr>
<% end %>
</table>

app/views/logs/show.html.erb
<h1>Log Analytics</h1>

<table>
  <tr>
    <th>Successful Requests</th>
    <th>Largest Request</th>
    <th>Total Requests</th>
    <th>Peak hour</th>
  </tr>
 
  <tr>
    <td><%= @suc_req %></td>
    <td><%= "#{@lar_req.values[0]} - #{@lar_req.keys[0]} kb" %></td>
    <td><%= @tota_req %></td>

    <td><%= "#{@max_hour_req[0].split[0]} from #{@max_hour_req[0].split[1]} to #{@max_hour_req[0].split[1].to_i+1} - #{@max_hour_req[1]} requests".html_safe %></td>
  </tr>
</table>